### ISSUE TITLE
setThumb() doesn't set a custom thumb on Android 4.3

### ISSUE THREAD

**Issue by colintheshots** [ahmedrizwan/SeekBarCompat#10]
I'm testing using a Samsung Galaxy S3 running 4.3. The setThumb() method fails to set a custom thumb on this version. It works fine on Lollipop, as expected.

**Comment by ahmedrizwan** [comment]
Hi @colintheshots, I've updated the library - tested it on S3 emulator running 4.3, and setThumb() seems to be working. Kindly update to version 0.2.5 and see if it works. Thanks!
