### ISSUE TITLE
 It does not have preview for android studio?

### ISSUE THREAD

**Issue by thyerrimezzari** [ahmedrizwan/SeekBarCompat#12]
![layout-2016-10-01-105722](https://cloud.githubusercontent.com/assets/13538408/19014538/e6537336-87c5-11e6-957b-a9106d92560a.png)

**Comment by boswelja** [comment]
My preview is working fine

**Comment by ahmedrizwan** [comment]
Yes @thyerrimezzari I think you needed to build the project once... Then it would've worked fine...
