### ISSUE TITLE
Application label conflict

### ISSUE THREAD

**Issue by pablode** [ahmedrizwan/SeekBarCompat#2]
Tried using the library by adding compile 'com.minimize.library:seekbar-compat:0.1.2' to my dependencies, but encountered an error.

> Error:(13, 9) Attribute application@label value=(@string/launcher_title) from AndroidManifest.xml:13:9
> Error:(13, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/launcher_title) from AndroidManifest.xml:13:9
>     is also present at com.minimize.library:seekbar-compat:0.1.2:13:9 value=(@string/app_name)
>     Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:11:5 to override

Is there any need for the application tags, or more specifically the android:label tag in the [Manifest.xml](https://github.com/ahmedrizwan/SeekBarCompat/blob/master/seekbar-compat/src/main/AndroidManifest.xml)? This is obviously a library, not an app.

**Comment by ahmedrizwan** [comment]
Yea you're right! I'll fix it in a minute - Thanks for pointing it out!

**Comment by ahmedrizwan** [comment]
I've updated the library - try using   

``` Gradle
compile 'com.minimize.library:seekbar-compat:0.1.3'
```

And if it fails to resolve - you'll have to add this url to your project repositories

``` Gradle
repositories {
    maven {
        url  "http://dl.bintray.com/ahmedrizwan/maven" 
    }
}
```

Please check and let me know if the problem persists. Thanks!

**Comment by pablode** [comment]
Thank you, it works.
