### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by AkshayChordiya** [ahmedrizwan/SeekBarCompat#3]
Hi,

I love this library, thank you so much for implement it.
I can understand that `Thumb` of `SeekBar` required API 16 & up. Yet can you make this library compliant from API 14 & up.
I mean can I just skip calling `setThumbColor` methods from my app for API < 16.

I hope we can make it backward compatibility.

EDIT: I checked the source & I guess we can easily make it backward compatible, just need to put API condition. Let me know if you need my help

**Comment by ahmedrizwan** [comment]
Thank you for your feedback. :) 
And yes, I'll try and make it compatible. It might take me a few days, but I would want to make it consistent on all the APIs that it supports. 

Temporarily, I'll add your suggestion to the source code available on GitHub. But then you'll have to download the lib source, and add dependency manually. (Until I come up with a better solution in the upcoming release)

**Comment by AkshayChordiya** [comment]
I don't want to keep the backward compatibility exactly. Just want to make this library compatible with API 14 by skipping the `Thumb` on it while API > 16 can have the original functionality.
BTW @ahmedrizwan Thanks for reply.

**Comment by ahmedrizwan** [comment]
No problem Akshay :) - Apologies for the late response but I was working on fixing issues and making the Lib compatible with API 14. Well that is done now, it is now fully compatible with API 14 - and is consistent through out all the APIs it supports - upgrade to version 0.2.0 to get the latest update.
For further info - check out the ReadMe. Thanks!

**Comment by AkshayChordiya** [comment]
Thank you so much.
I'm so glad.

On Thu, Jul 9, 2015, 7:11 AM ahmed notifications@github.com wrote:

> Closed #3 https://github.com/ahmedrizwan/SeekBarCompat/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ahmedrizwan/SeekBarCompat/issues/3#event-351400820.
> 
> ## 

Regards,
Akshay Chordiya
