### ISSUE TITLE
Issue with devices & android version

### ISSUE THREAD

**Issue by AkshayChordiya** [ahmedrizwan/SeekBarCompat#5]
Hi,

This library is perfect for me. Moreover it is compatible down to API 14.
But when I tested on some other devices, it showed weird view & on some devices the `thumb` ahead of seek.
I appreciate your hard work. But is there any solution to these issues, because I can't go back to `Seekbar` as this library is awesome

**Comment by ahmedrizwan** [comment]
Thanks! Yea that is a problem I'm currently working on. It primarily is caused by padding. If you're giving padding to the seekbar in xml, it messes up the position of thumb as it progresses. 
Anyway I'll let you know when it gets fixed. :)

**Comment by AkshayChordiya** [comment]
@ahmedrizwan 
Yeah the `thumb` is solved by removing the padding but few devices have improper `SeekBar` that is yet to fix & I'll wait till it is

**Comment by ahmedrizwan** [comment]
Library update to 0.2.1 version. I have solved the padding and speeding issue, do make sure to specify maxHeight attribute for proper thumb gravity. Thanks!
