### ISSUE TITLE
Version 0.2.1 on Jellybean

### ISSUE THREAD

**Issue by shinayser** [ahmedrizwan/SeekBarCompat#6]
Today I compiled my code with the new version 0.2.1 on a tablet 4.1 Jellybean, and this is what happened:
![screenshot_2015-07-21-15-58-12](https://cloud.githubusercontent.com/assets/1146982/8809990/3a58e2ca-2fc2-11e5-997b-d1f57720ede0.png)

Works fine on 0.2.0!

Thankyou so much for such great lib =)

**Comment by ahmedrizwan** [comment]
Thankyou! :) glad you liked the library - The library had a few bugs, so I fixed updated it today... But now you'll have to add **maxHeight** attribute in xml. That fixes the gravity issue. 
Unfortunately there's no other work-around currently. If I figure something out then I'll incorporate that. For now, do try and let me know :) 
Add in your xml, something like: - 
android:maxHeight="300sp"

**Comment by shinayser** [comment]
Yeah it worked!! But for some reason i realized that the rounded "thumb" has lost a lot of quality (it is very pixelated). Is something me I missing?

**Comment by ahmedrizwan** [comment]
Yea I think that problem was caused because I shifted over to using Bitmaps... I have updated the library yet again, I'm using GradientDrawables - the quality should be better now.
So update to version 0.2.2 and let me know.
Thanks!

**Comment by shinayser** [comment]
It's workign perfectly now!!!
Theere is just one last question: In lollipop, when setting the seekbar disabled with setEnabled(false), the seekbar gets completely invislbe. In Jellybean works nice! Am i missing something?

Thankyou again for yoru support Ahmed!

**Comment by ahmedrizwan** [comment]
Oh ok - Thank you shinayser for finding these issues. :) Really appreciate it!
And yes I don't know why that's happening, but I'll look into it. Will let you know when fixed.

Thanks!

**Comment by ahmedrizwan** [comment]
setEnabled() should work now - update to version 0.2.3.
Thanks! :)

**Comment by shinayser** [comment]
Hey Ahmed!
I just tested and here is what is going on:
1. In lollipop setEnabled() does nothing, the bar remains visible but can still be swiped and doesnt get "grey" aspect.
2. In Jellybean the bar gets "grey" aspect and really gets disabled, but i can't go back to the enabled state (it remains disabled all time).

Haha! We are getting close!! :D

**Comment by ahmedrizwan** [comment]
Haha! Yes we are! :D Will work on it today - and will let you know after a fix. 
Thank you for testing these out man! :)
