### ISSUE TITLE
Weird space on KitKat

### ISSUE THREAD

**Issue by AkshayChordiya** [ahmedrizwan/SeekBarCompat#7]
Hi there,

The `SeekbarCompat` works great on Lollipop but it is creating a useless space on KitKat.
See the image attached for clear understanding

![2015-07-23](https://cloud.githubusercontent.com/assets/3120052/8889857/4f3389ee-3309-11e5-848b-59cf140ff464.png)

**Comment by ahmedrizwan** [comment]
I can't access the attached image. Can you please make it public?
Thanks

**Comment by AkshayChordiya** [comment]
@ahmedrizwan 
Sorry for inconvenience, the image is showing now

**Comment by ahmedrizwan** [comment]
No problem :) can you please also share a screenshot of lollipop version so I can compare the two?

**Comment by AkshayChordiya** [comment]
@ahmedrizwan 
In the lollipop, it's the same except that the background of `SeekbarCompat` is the blue color

**Comment by Div-e-Sepid** [comment]
add this line of code to the seekBar:

``` java
    android:maxHeight="300sp"
```
